### ISSUE TITLE
🚀 [Feature] Deal 상세조회 및 노트작성 관련 API

### ISSUE THREAD

**Issue by koojun99** [InnoSage/CRM-BE#25]
# 🤖 기능 개요

Deal 상세조회 및 노트작성 관련 API
## ✅ Todo
- [x] **GET** /sheet/{sheetId}/deals/{dealId}
- [x] **POST** /sheet/{sheetId}/deals/{dealId}/contents
- [ ] **GET** /deals/{dealId}/notes
- [ ] **GET** /deals/{dealId}/notes/{noteId}
- [ ] **POST** /deals/{dealId}/notes
- [ ] **PATCH** /deals/{dealId}/notes/{noteId}
- [ ] **DELETE** /deals/{dealId}/notes/{noteId}
